
// Common data for autocomplete suggestions across the application

// Indian States
export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

// Union Territories
export const indianUnionTerritories = [
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

// Combine states and union territories
export const allIndianRegions = [...indianStates, ...indianUnionTerritories];

// Common professions/job categories
export const professions = [
  "Carpenter",
  "Plumber",
  "Electrician",
  "Painter",
  "Mason",
  "Mechanic",
  "Driver",
  "Chef",
  "Cleaner",
  "Security Guard",
  "Gardener",
  "Tailor",
  "Construction Worker",
  "Welder",
  "HVAC Technician",
  "Roofer",
  "Landscaper",
  "Appliance Repair",
  "Flooring Installer",
  "Glass Installer",
  "Handyman",
  "Home Inspector",
  "Interior Designer",
  "Locksmith",
  "Pest Control",
];

// Languages spoken in India
export const indianLanguages = [
  "Hindi",
  "English",
  "Bengali",
  "Telugu",
  "Marathi",
  "Tamil",
  "Urdu",
  "Gujarati",
  "Kannada",
  "Odia",
  "Malayalam",
  "Punjabi",
  "Assamese",
  "Maithili",
  "Sanskrit",
];

// Skills relevant to professions
export const skills = [
  "Woodworking",
  "Piping",
  "Wiring",
  "Circuit Repair",
  "Welding",
  "Painting",
  "Plastering",
  "Bricklaying",
  "Tiling",
  "Engine Repair",
  "Plumbing",
  "Electrical Work",
  "Carpentry",
  "Masonry",
  "HVAC",
  "Roofing",
  "Flooring",
  "Drywall Installation",
  "Cabinet Making",
  "Concrete Work",
  "Equipment Operation",
  "Blueprint Reading",
  "Precision Measurement",
  "Power Tool Operation",
  "Safety Procedures",
  "Maintenance",
  "Troubleshooting",
  "Installation",
  "Repair",
  "Customer Service",
];

// Common search terms users might look for
export const commonSearchTerms = [
  "Electrician near me",
  "Plumber for bathroom",
  "Carpenter for furniture",
  "House painter",
  "Emergency plumber",
  "Gardener weekly service",
  "Kitchen renovation worker",
  "Bathroom remodeling",
  "Handyman for small jobs",
  "Air conditioner repair",
  "Roof repair",
  "Electrician for wiring",
  "Plumber for leaking pipe",
  "Carpenter for door repair",
  "Painters for house exterior",
  "Carpenter for furniture assembly",
  "Driver for local travel",
  "Cleaner for home",
  "Security guard for event",
  "Gardener for landscaping",
];

// Popular locations
export const popularLocations = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Surat",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Patna",
  "Vadodara",
  "Ghaziabad",
];
